server:
  port: 8081
spring:
  application:
    name: ms-mail-sender
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    function:
      definition: fromConfirmEmailConsumer;fromConfirmInscriptionConsumer
    stream:
      default-binder: rabbit
      bindings:
        fromConfirmEmailConsumer-in-0:
          destination: confirmEmail
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            concurrency: 30
        fromConfirmInscriptionConsumer-in-0:
          destination: confirmInscription
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            concurrency: 30
      rabbit:
        bindings:
          fromConfirmEmailConsumer-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
          fromConfirmInscriptionConsumer-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.event_hub: DEBUG

app:
  environment:
    url: ${APP_ENVIRONMENT_URL:http://localhost:8080}