server:
  port: 8082
spring:
  application:
    name: ms-user
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users_event_hub
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        toConfirmEmailConsumer-out-0:
          destination: confirmEmail
          content-type: application/json
          group: ${spring.application.name}
      rabbit:
        bindings:
          toConfirmEmailConsumer-out-0:
            producer:
              transacted: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    redis:
      enabled: true
    mongodb:
      enabled: true
springdoc:
  swagger-ui:
    path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka