server:
  port: 8080
spring:
  application:
    name: event-hub
  data:
    mongodb:
      host: localhost
      port: 27017
      database: event_hub
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    redis:
      enabled: true
    mongodb:
      enabled: true
springdoc:
  swagger-ui:
    path: /
app:
  environment:
    url: ${APP_ENVIRONMENT_URL:http://localhost:8080}