server:
  port: 8080
spring:
  application:
    name: event-hub
  data:
    mongodb:
      host: localhost
      port: 27017
      database: event_hub
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        toConfirmEmailConsumer-out-0:
          destination: confirmEmail
          content-type: application/json
          group: ${spring.application.name}
        toConfirmInscriptionConsumer-out-0:
          destination: confirmInscription
          content-type: application/json
          group: ${spring.application.name}
      rabbit:
        bindings:
          toConfirmEmailConsumer-out-0:
            producer:
              transacted: true
          toConfirmInscriptionConsumer-out-0:
            producer:
              transacted: true
              exchange-type: fanout
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    redis:
      enabled: true
    mongodb:
      enabled: true
springdoc:
  swagger-ui:
    path: /
app:
  environment:
    url: ${APP_ENVIRONMENT_URL:http://localhost:8080}